//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Embassy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmbassyEntitiesFramework : DbContext
    {
        public EmbassyEntitiesFramework()
            : base("name=EmbassyEntitiesFramework")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Meeting> Meeting { get; set; }
        public virtual DbSet<Office> Office { get; set; }
        public virtual DbSet<Participates> Participates { get; set; }
        public virtual DbSet<Visa> Visa { get; set; }
    }
}
