//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Embassy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participates
    {
        public int Id { get; set; }
        public int Employee { get; set; }
        public int Meeting { get; set; }
    
        public virtual Employee Employee1 { get; set; }
        public virtual Meeting Meeting1 { get; set; }
    }
}
