//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Embassy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visa
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public System.DateTime Expiration { get; set; }
        public int Granted_by { get; set; }
        public string Received_by { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
